# Generated by Django 4.2.5 on 2023-09-17 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(null=True, upload_to='accounts/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=100)),
                ('apartment_suite', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_admin.accounts')),
            ],
        ),
        migrations.RemoveField(
            model_name='categories',
            name='Shop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Shop',
        ),
        migrations.DeleteModel(
            name='Shopadmin',
        ),
    ]
