# Generated by Django 4.2.5 on 2023-09-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admin', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
